import { Signal } from "../../Signal/Signal.js"

/**
 * @typedef {Object} ARIAMixinProperties
 * @property {string | null | Signal<string | null>} [ariaAtomic] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaAtomic)
 * @property {string | null | Signal<string | null>} [ariaAutoComplete] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaAutoComplete)
 * @property {string | null | Signal<string | null>} [ariaBrailleLabel] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaBrailleLabel)
 * @property {string | null | Signal<string | null>} [ariaBrailleRoleDescription] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaBrailleRoleDescription)
 * @property {string | null | Signal<string | null>} [ariaBusy] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaBusy)
 * @property {string | null | Signal<string | null>} [ariaChecked] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaChecked)
 * @property {string | null | Signal<string | null>} [ariaColCount] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaColCount)
 * @property {string | null | Signal<string | null>} [ariaColIndex] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaColIndex)
 * @property {string | null | Signal<string | null>} [ariaColIndexText] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaColIndexText)
 * @property {string | null | Signal<string | null>} [ariaColSpan] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaColSpan)
 * @property {string | null | Signal<string | null>} [ariaCurrent] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaCurrent)
 * @property {string | null | Signal<string | null>} [ariaDescription] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaDescription)
 * @property {string | null | Signal<string | null>} [ariaDisabled] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaDisabled)
 * @property {string | null | Signal<string | null>} [ariaExpanded] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaExpanded)
 * @property {string | null | Signal<string | null>} [ariaHasPopup] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaHasPopup)
 * @property {string | null | Signal<string | null>} [ariaHidden] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaHidden)
 * @property {string | null | Signal<string | null>} [ariaInvalid]
 * @property {string | null | Signal<string | null>} [ariaKeyShortcuts] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaKeyShortcuts)
 * @property {string | null | Signal<string | null>} [ariaLabel] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaLabel)
 * @property {string | null | Signal<string | null>} [ariaLevel] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaLevel)
 * @property {string | null | Signal<string | null>} [ariaLive] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaLive)
 * @property {string | null | Signal<string | null>} [ariaModal] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaModal)
 * @property {string | null | Signal<string | null>} [ariaMultiLine] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaMultiLine)
 * @property {string | null | Signal<string | null>} [ariaMultiSelectable] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaMultiSelectable)
 * @property {string | null | Signal<string | null>} [ariaOrientation] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaOrientation)
 * @property {string | null | Signal<string | null>} [ariaPlaceholder] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaPlaceholder)
 * @property {string | null | Signal<string | null>} [ariaPosInSet] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaPosInSet)
 * @property {string | null | Signal<string | null>} [ariaPressed] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaPressed)
 * @property {string | null | Signal<string | null>} [ariaReadOnly] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaReadOnly)
 * @property {string | null | Signal<string | null>} [ariaRequired] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaRequired)
 * @property {string | null | Signal<string | null>} [ariaRoleDescription] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaRoleDescription)
 * @property {string | null | Signal<string | null>} [ariaRowCount] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaRowCount)
 * @property {string | null | Signal<string | null>} [ariaRowIndex] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaRowIndex)
 * @property {string | null | Signal<string | null>} [ariaRowIndexText] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaRowIndexText)
 * @property {string | null | Signal<string | null>} [ariaRowSpan] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaRowSpan)
 * @property {string | null | Signal<string | null>} [ariaSelected] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaSelected)
 * @property {string | null | Signal<string | null>} [ariaSetSize] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaSetSize)
 * @property {string | null | Signal<string | null>} [ariaSort] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaSort)
 * @property {string | null | Signal<string | null>} [ariaValueMax] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaValueMax)
 * @property {string | null | Signal<string | null>} [ariaValueMin] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaValueMin)
 * @property {string | null | Signal<string | null>} [ariaValueNow] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaValueNow)
 * @property {string | null | Signal<string | null>} [ariaValueText] [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/ariaValueText)
 * @property {string | null | Signal<string | null>} [role]
 */